version: '3.7'

services:
  app:
    restart: always
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - "5000:5000"
    env_file:
      - ./.env

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_db

volumes:
  static:
  postgres_data: {}