version: '3.7'

services:
  flask_gunicorn:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_gunicorn
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_db

volumes:
  static:
  postgres_data: